### ISSUE TITLE
继承于 BaseController 的类，无法再实现 Routerable 协议

### ISSUE THREAD

**Issue by PublicWorld** [lixiang1994/Router#3]
![set](https://user-images.githubusercontent.com/12987627/63209798-3ee3c080-c118-11e9-843b-dc9fa45aff83.png)

如图所示，SettingController 继承于 BaseViewController，然 `Routerable` 却是 `protocol Routerable: UIViewController` 继承于 `UIViewController` ···

**Comment by lixiang1994** [comment]
重写呢? 还有不是所有页面都要支持外部路由的吧? 我见过的项目 可以让外部打开的页面数量不会太多的, 毕竟不是所有页面都那么解耦独立的

**Comment by PublicWorld** [comment]
😅 那估计只能手动导入本框架源码，重写这个协议继承于 BaseController 了。

**Comment by lixiang1994** [comment]
我是说你BaseViewController实现了Routerable, 那么你的子类可以通过重写 open 和 close的实现来解决吧?

**Comment by PublicWorld** [comment]
看来那 Router 就得放入 Base 基础组件耦合了。

**Comment by PublicWorld** [comment]
但我有 BaseController ，还有 BaseTableController，头大 ... 
感觉得换个方式解决这个问题。

**Comment by PublicWorld** [comment]
为啥这个协议 UIViewController 子类的子类居然就无法实现了呢。😥

**Comment by PublicWorld** [comment]
沃日特，是沙雕 Xcode 的原因，瞎提示。
我把 Basic 模块 import 了，再继承 BaseVC ，就没事了。。😅
